extends SceneTree
## CPU-only ABI/math checks for the main-RD ray-input generator.

const Generator = preload("res://addons/feng-fog/rendering/raytracing/fog_rt_ray_input_generator.gd")
const ShadowProvider = preload("res://addons/feng-fog/rendering/raytracing/fog_rt_shadow_provider.gd")

var _checks := 0
var _failures := 0


func _initialize() -> void:
	call_deferred("_run")


func _require(p_condition: bool, p_message: String) -> void:
	_checks += 1
	if not p_condition:
		_failures += 1
		push_error("REGRESSION: " + p_message)


func _run() -> void:
	var generator = Generator.new()
	var contract: Dictionary = generator.get_contract()
	_require(int(contract.get("abi_version", 0)) == 2,
			"ray record ABI v2 assigns the former reserved lanes to mask and participation")
	_require(int(contract.get("ray_record_stride_bytes", 0)) == 48
			and int(contract.get("ray_frame_uniform_bytes", 0)) == 256,
			"ray records and independent RayFrame retain their fixed byte layouts")
	var ray_fields: Array = contract.get("ray_fields", [])
	var cone_field: Dictionary = ray_fields[2] if ray_fields.size() == 3 else {}
	_require(cone_field.get("name") == "cone_words"
			and int(cone_field.get("offset", -1)) == 32
			and cone_field.get("format") == "uvec4 raw words"
			and str(cone_field.get("meaning", "")).contains("raw uint32 light mask"),
			"the third 16-byte lane is documented as raw uint words at byte offset 32")
	_require(int(contract.get("depth_parameters_uniform_bytes", 0)) == 144
			and int(contract.get("depth_sampler_binding", -1)) == 7
			and int(contract.get("depth_parameters_binding", -1)) == 8,
			"current depth uses a separate 144-byte projection UBO and bindings 7/8")
	_require(int(contract.get("work_mask_parameters_uniform_bytes", 0)) == 16
			and int(contract.get("work_mask_storage_binding", -1)) == 9
			and int(contract.get("work_mask_parameters_binding", -1)) == 10,
			"optional work masks use a borrowed uint SSBO and independent 16-byte binding-10 UBO")
	_require(int(contract.get("light_extension_set", -1)) == 3
			and contract.get("light_extension_bindings", []) == [0, 1, 2]
			and int(contract.get("light_extension_abi_version", 0)) == 2
			and int(contract.get("light_extension_record_stride_bytes", 0)) == 144,
			"SourceLength reads the shared same-frame set-3 ABI v2 record without another record layout")
	_require(not Generator.depth_constraint_requested({}, {"gbuffer_completed": true})
			and not Generator.depth_constraint_requested({"depth_prepass_enabled": true}, {})
			and Generator.depth_constraint_requested({"depth_prepass_enabled": true},
				{"gbuffer_completed": true}),
			"depth constraints require both completed GBuffer and the frame depth-prepass flag")
	_require(contract.get("visibility_values") == {"blocked": 0, "visible_or_inactive_neutral": 1},
			"inactive sources preserve the binary visibility protocol with neutral one")
	_require(str(contract.get("input_lights", "")).contains("8-byte (type,index) slots")
			and not bool(contract.get("gpu_readback", true)),
			"only small light descriptors cross CPU and all rays stay GPU-generated")
	var ray_shader := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_rt_ray_input_generate.glslinc")
	var raygen_source := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_shadow_raygen.glslinc")
	var any_hit_source := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_shadow_any_hit.glslinc")
	var closest_hit_source := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_shadow_closest_hit.glslinc")
	var miss_source := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_shadow_miss.glslinc")
	var provider_source := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_rt_shadow_provider.gd")
	var generator_source := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_rt_ray_input_generator.gd")
	_require(ray_shader.begins_with("#[compute]\n#version 450")
			and ray_shader.contains("writeonly buffer FogShadowRayInputs"),
			"ray records are generated by a valid RD compute shader, not CPU byte filling")
	var raw_compute_source := Generator.strip_compute_marker(ray_shader)
	_require(raw_compute_source.begins_with("#version 450")
			and not raw_compute_source.contains("#[compute]"),
			"RD raw GLSL removes the Godot-only compute importer hint")
	_require(ray_shader.contains("FRP_NATIVE_LIGHT_ABI_INSERT")
			and ray_shader.contains("FRPVolumeDirectionalLightData")
			and ray_shader.contains("FRPVolumeLightData"),
			"generator consumes the canonical native 464/224-byte light structure include")
	_require(ray_shader.contains("FRP_LIGHT_EXTENSION_ABI_INSERT")
			and ray_shader.contains("ffog_light_extension_record_index")
			and ray_shader.contains("ffog_light_capsule_source_length_m")
			and ray_shader.contains("ffog_light_capsule_axis_world")
			and generator_source.contains("p_light_extension_inputs: Dictionary = {}")
			and generator_source.contains("p_rd.compute_list_bind_uniform_set(compute_list, extension_uniform_set, LIGHT_EXTENSION_SET)"),
			"RT generator binds and consumes the exact shared light-extension set-3 ABI")
	_require(ray_shader.contains("inverse_projection")
			and ray_shader.contains("viewport_pixel_jitter_x")
			and ray_shader.contains("log_depth_near")
			and ray_shader.contains("eye_offset_center_view")
			and ray_shader.contains("vec3 sample_offset = vec3(sample_xy, ray_frame.ray_limits_far.w)")
			and ray_shader.contains("float(p_cell.z) + p_sample_offset.z"),
			"independent RayFrame reconstructs unjittered per-eye froxels and native center-view positions")
	_require(ray_shader.contains("binding = 7) uniform sampler2D current_scene_depth")
			and ray_shader.contains("binding = 8, std140) uniform RayDepthParameters")
			and ray_shader.contains("feng_ray_depth_constrained_slice")
			and ray_shader.contains("depth_slice_with_offset = scene_slice - ray_depth.control.y")
			and ray_shader.contains("return max(float(p_cell.z) + p_sample_offset.z, 0.0)")
			and ray_shader.contains("max(p_slice, 0.0) / max(ray_frame.log_depth_near.z"),
			"RT generator samples only a separately bound current depth layer and mirrors the volume depth constraint")
	_require(generator_source.contains("p_depth_options: Dictionary = {}")
			and generator_source.contains("gbuffer_completed")
			and generator_source.contains("depth_prepass_enabled")
			and generator_source.contains("TEXTURE_USAGE_SAMPLING_BIT")
			and not generator_source.contains("texture_copy("),
			"depth constraint requires GBuffer completion and a sampleable depth layer without unsafe copy/blit assumptions")
	_require(generator_source.contains("p_work_mask_options: Dictionary = {}")
			and ray_shader.contains("binding = 9, std430) readonly buffer FogRayWorkMask")
			and ray_shader.contains("binding = 10, std140) uniform RayWorkMaskParameters")
			and ray_shader.contains("ray_work_mask_parameters.values.x >= fog_ray_work_mask.requested_sample_count[froxel_index]")
			and not generator_source.contains("buffer_get_data("),
			"work-mask sample counts are checked on GPU without copying mask data to CPU")
	_require(generator_source.contains("validate_light_extension_inputs")
			and generator_source.contains("records_buffer_capacity_bytes")
			and generator_source.contains("native_type_counts")
			and generator_source.contains("record_offsets")
			and generator_source.contains("frame_generation")
			and not generator_source.contains("buffer_get_data("),
			"same-frame set-3 metadata is validated structurally without CPU readback")
	var valid_work_mask_rid := RenderingServer.mesh_create()
	var valid_mask_options := {
		"enabled": true,
		"mask_buffer": valid_work_mask_rid,
		"mask_capacity_bytes": 256,
		"frame_generation": 17,
		"froxel_count": 64,
		"sample_index": 3,
		"max_samples": 4,
	}
	_require(bool(Generator.validate_work_mask_options({}, 17, 64).get("valid", false))
			and not bool(Generator.validate_work_mask_options({}, 17, 64).get("enabled", true)),
			"omitting work-mask options preserves the original all-samples-active path")
	_require(bool(Generator.validate_work_mask_options({"enabled": false}, 17, 64).get("valid", false)),
			"an explicitly disabled work mask needs no borrowed buffer")
	_require(bool(Generator.validate_work_mask_options(valid_mask_options, 17, 64).get("valid", false)),
			"matching work-mask RID, capacity, generation, grid, and sample index are accepted")
	var stale_work_mask := valid_mask_options.duplicate()
	stale_work_mask["frame_generation"] = 16
	_require(not bool(Generator.validate_work_mask_options(stale_work_mask, 17, 64).get("valid", true)),
			"stale work-mask frame generations fail closed to raster fallback")
	var undersized_work_mask := valid_mask_options.duplicate()
	undersized_work_mask["mask_capacity_bytes"] = 252
	_require(not bool(Generator.validate_work_mask_options(undersized_work_mask, 17, 64).get("valid", true)),
			"work-mask capacity must hold one uint for every froxel")
	var wrong_grid_work_mask := valid_mask_options.duplicate()
	wrong_grid_work_mask["froxel_count"] = 63
	_require(not bool(Generator.validate_work_mask_options(wrong_grid_work_mask, 17, 64).get("valid", true)),
			"work-mask froxel count must match the frame grid")
	var out_of_range_sample := valid_mask_options.duplicate()
	out_of_range_sample["sample_index"] = 4
	_require(not bool(Generator.validate_work_mask_options(out_of_range_sample, 17, 64).get("valid", true)),
			"sample indices outside the global max-sample budget are rejected")
	_require(not bool(Generator.validate_work_mask_options({"enabled": true}, 17, 64).get("valid", true)),
			"an enabled mask without its borrowed RID and metadata cannot silently disable shadows")
	var packed_work_mask := Generator.pack_work_mask_parameters_uniform(valid_mask_options, 0x100000011)
	_require(packed_work_mask.size() == 16 and packed_work_mask.decode_s32(0) == 3
			and packed_work_mask.decode_s32(4) == 1 and packed_work_mask.decode_u32(8) == 17,
			"binding-10 packs sample index, enabled flag, and low frame-generation bits")
	_require(not Generator.work_mask_sample_is_active(0, 0, 4)
			and Generator.work_mask_sample_is_active(0, 1, 4)
			and not Generator.work_mask_sample_is_active(1, 1, 4)
			and Generator.work_mask_sample_is_active(3, 4, 4),
			"per-froxel work counts preserve zero-occluded, valid-history, and full-miss cases")
	var extension_rid := RenderingServer.mesh_create()
	var extension_frame := {
		"frame_generation": 23,
		"omni_light_count": 2,
		"spot_light_count": 1,
		"area_light_count": 1,
		"directional_light_count": 1,
	}
	var extension_inputs := {
		"valid": true,
		"abi_version": 2,
		"record_stride_bytes": 144,
		"record_count": 5,
		"native_type_counts": PackedInt32Array([2, 1, 1, 1]),
		"record_offsets": {"omni": 0, "spot": 2, "area": 3, "directional": 4},
		"records_buffer": extension_rid,
		"records_buffer_capacity_bytes": 5 * 144,
		"cookie_texture_array": extension_rid,
		"cookie_sampler": extension_rid,
		"cookie_layer_count": 0,
		"header_buffer": extension_rid,
		"frame_generation": 23,
	}
	var extension_validation := Generator.validate_light_extension_inputs(
			extension_inputs, extension_frame)
	_require(bool(Generator.validate_light_extension_inputs({}, extension_frame).get("valid", false))
			and not bool(Generator.validate_light_extension_inputs({}, extension_frame).get("enabled", true)),
			"omitting extension inputs preserves the legacy native-size radius-disk path")
	_require(bool(extension_validation.get("valid", false))
			and bool(extension_validation.get("enabled", false))
			and int(extension_validation.get("record_count", 0)) == 5,
			"matching provider-owned set-3 records, cookie bindings, counts, offsets, and frame lease are accepted")
	var stale_extension := extension_inputs.duplicate(true)
	stale_extension["frame_generation"] = 22
	_require(not bool(Generator.validate_light_extension_inputs(stale_extension,
			extension_frame).get("valid", true)),
			"stale set-3 generation fails closed before ray dispatch")
	var wrong_extension_stride := extension_inputs.duplicate(true)
	wrong_extension_stride["record_stride_bytes"] = 128
	_require(not bool(Generator.validate_light_extension_inputs(wrong_extension_stride,
			extension_frame).get("valid", true)),
			"a different light-extension record stride cannot be reinterpreted as ABI v2")
	var wrong_extension_counts := extension_inputs.duplicate(true)
	wrong_extension_counts["native_type_counts"] = PackedInt32Array([1, 1, 1, 1])
	_require(not bool(Generator.validate_light_extension_inputs(wrong_extension_counts,
			extension_frame).get("valid", true)),
			"set-3 counts must match this viewport's native light buffer ordering")
	var wrong_extension_offsets := extension_inputs.duplicate(true)
	wrong_extension_offsets["record_offsets"] = {"omni": 0, "spot": 1, "area": 3, "directional": 4}
	_require(not bool(Generator.validate_light_extension_inputs(wrong_extension_offsets,
			extension_frame).get("valid", true)),
			"record offsets must retain the provider's omni/spot/area/directional order")
	var undersized_extension_buffer := extension_inputs.duplicate(true)
	undersized_extension_buffer["records_buffer_capacity_bytes"] = 5 * 144 - 1
	_require(not bool(Generator.validate_light_extension_inputs(undersized_extension_buffer,
			extension_frame).get("valid", true)),
			"record buffer capacity is checked against the complete current frame")
	var extension_counts := PackedInt32Array([2, 1, 1, 1])
	_require(Generator.extension_record_index_cpu(Generator.LIGHT_OMNI, 1,
			extension_counts) == 1
			and Generator.extension_record_index_cpu(Generator.LIGHT_SPOT, 0,
			extension_counts) == 2
			and Generator.extension_record_index_cpu(Generator.LIGHT_AREA, 0,
			extension_counts) == 3
			and Generator.extension_record_index_cpu(Generator.LIGHT_DIRECTIONAL, 0,
			extension_counts) == 4,
			"native slot kinds join the same flattened extension record indices")
	_require(Generator.extension_record_index_cpu(Generator.LIGHT_OMNI, 2,
			extension_counts) == -1,
			"a native light slot cannot index beyond the set-3 type count")
	var light_basis := Basis(Vector3.FORWARD, PI * 0.5)
	var camera_basis := Basis(Vector3.FORWARD, -PI * 0.5)
	var world_to_light := Transform3D(light_basis.transposed(), Vector3(50.0, 20.0, -10.0))
	var view_to_world := Transform3D(camera_basis, Vector3(-100.0, 40.0, 20.0))
	var center_axis := Generator.capsule_axis_center_view_cpu(world_to_light,
			view_to_world, 0)
	var expected_world_axis := light_basis * Vector3.RIGHT
	var expected_center_axis := (camera_basis.transposed() * expected_world_axis).normalized()
	_require(center_axis.is_equal_approx(expected_center_axis)
			and is_equal_approx(center_axis.length(), 1.0),
			"capsule axis maps local to world to center-view using rotation only, without translation or eye offset")
	var capsule_center := Vector3(2.0, 3.0, 4.0)
	_require(Generator.capsule_source_sample_cpu(capsule_center, Vector3.RIGHT,
			2.0, 0.0).is_equal_approx(Vector3(1.0, 3.0, 4.0))
			and Generator.capsule_source_sample_cpu(capsule_center, Vector3.RIGHT,
			2.0, 0.5).is_equal_approx(capsule_center)
			and Generator.capsule_source_sample_cpu(capsule_center, Vector3.RIGHT,
			2.0, 1.0).is_equal_approx(Vector3(3.0, 3.0, 4.0))
			and Generator.capsule_source_sample_cpu(capsule_center, Vector3.RIGHT,
			0.0, 0.0).is_equal_approx(capsule_center),
			"independent capsule samples cover both endpoints and center while zero length is neutral")
	var capsule_ray_source := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_rt_ray_input_generate.glslinc")
	_require(capsule_ray_source.contains("float random_line = feng_ray_random(seed)")
			and capsule_ray_source.contains("ray_work_mask_parameters.values.x * 0xc2b2ae35u")
			and capsule_ray_source.contains("source_position += axis_center_view")
			and capsule_ray_source.contains("else if (p_light.size > 0.0)")
			and capsule_ray_source.find("float distance_to_source = length(to_source)")
			> capsule_ray_source.find("source_position += axis_center_view"),
			"capsule uses an independent random dimension, keeps native size as the zero-length radius path, and measures maxT to the sampled source")
	if extension_rid.is_valid():
		RenderingServer.free_rid(extension_rid)
	if valid_work_mask_rid.is_valid():
		RenderingServer.free_rid(valid_work_mask_rid)
	var center_camera_origin := Vector3(3.0, 4.0, 5.0)
	var eye_offset := Vector3(0.25, -0.5, 0.75)
	var per_eye_view_position := Vector3(1.0, 2.0, -7.0)
	var per_eye_transform := Transform3D(Basis.IDENTITY, center_camera_origin + eye_offset)
	var world_position := per_eye_transform * per_eye_view_position
	var recovered_center_view := world_position - center_camera_origin
	_require(recovered_center_view.is_equal_approx(per_eye_view_position + eye_offset)
			and ray_shader.contains("view_position + ray_frame.eye_offset_center_view.xyz")
			and not ray_shader.contains("view_position - ray_frame.eye_offset_center_view.xyz"),
			"nonzero per-eye offsets map to native center-view coordinates with a plus sign")
	_require(ray_shader.contains("p_light.volumetric_fog_energy > 0.0")
			and ray_shader.contains("p_light.shadow_opacity > 0.001")
			and ray_shader.contains("p_light.area_width"),
			"GPU source selection checks actual shadow/volume flags and area-emitter geometry")
	_require(raygen_source.contains("#if FENG_FOG_RAY_ABI == 2")
			and raygen_source.contains("light_mask == 0u")
			and raygen_source.contains("visible[ray_index] = 1u")
			and not raygen_source.contains("visible[ray_index] = 2u"),
			"ABI 2 compile-time variant skips inactive/mask-zero rays while keeping binary neutral visibility")
	_require(raygen_source.contains("layout(location = 0) rayPayloadEXT uint visibility")
			and any_hit_source.contains("layout(location = 0) rayPayloadInEXT uint visibility")
			and closest_hit_source.contains("layout(location = 0) rayPayloadInEXT uint visibility")
			and miss_source.contains("layout(location = 0) rayPayloadInEXT uint visibility")
			and any_hit_source.contains("rays[gl_LaunchIDEXT.x]")
			and not any_hit_source.contains("payload.ray_index")
			and not raygen_source.contains("ray_index;"),
			"all four RT stages share a single uint payload and any-hit indexes the inherited launch ID")
	_require(raygen_source.contains("visibility = 1u;")
			and raygen_source.contains("visible[ray_index] = visibility;")
			and closest_hit_source.contains("visibility = 0u;")
			and miss_source.contains("visibility = 1u;"),
			"raygen starts visible, accepted hits block, and miss explicitly restores visible")
	_require(ray_shader.contains("uvec4 cone_words;")
			and ray_shader.contains("light_mask, floatBitsToUint(ray_active ? 1.0 : 0.0)")
			and raygen_source.contains("uint light_mask = ray.cone_words.z")
			and raygen_source.contains("uintBitsToFloat(ray.cone_words.w)")
			and raygen_source.contains("#if FENG_FOG_RAY_ABI == 2")
			and any_hit_source.contains("uint light_mask = ray.cone_words.z")
			and any_hit_source.contains("uintBitsToFloat(ray.cone_words.x)")
			and any_hit_source.contains("uintBitsToFloat(ray.cone_words.y)")
			and any_hit_source.contains("instance.w & light_mask")
			and not any_hit_source.contains("floatBitsToUint(ray.cone_words.z)"),
			"mask lane is consumed as raw uint while only float-valued radius, growth, and active lanes are bit-converted")
	var literal_mask_words_ok := true
	var mask_values: Array[int] = [1 << 20, 1 << 31, 0xffffffff, 0]
	for mask_value in mask_values:
		var ray_record := PackedByteArray()
		ray_record.resize(48)
		ray_record.encode_float(32, 0.125)
		ray_record.encode_float(36, 0.25)
		ray_record.encode_u32(40, mask_value)
		ray_record.encode_float(44, 1.0)
		literal_mask_words_ok = literal_mask_words_ok and (
				ray_record.decode_u32(32) == 0x3e000000
				and ray_record.decode_u32(36) == 0x3e800000
				and ray_record.decode_u32(40) == mask_value
				and ray_record.decode_u32(44) == 0x3f800000
		)
	_require(literal_mask_words_ok,
			"48-byte raw-word layout preserves bit20, bit31, all-ones and zero masks exactly without float transport")
	var provider := ShadowProvider.new()
	var provider_contract: Dictionary = provider.get_ray_input_contract()
	var shader_variant: Dictionary = provider_contract.get("shader_variant", {})
	var descriptor_bindings: Dictionary = provider_contract.get("descriptor_bindings", {})
	var abi1_raygen := ShadowProvider.shader_source_for_abi(raygen_source, 1)
	var abi2_any_hit := ShadowProvider.shader_source_for_abi(any_hit_source, 2)
	var abi1_define_index := abi1_raygen.find("#define FENG_FOG_RAY_ABI 1")
	var abi2_define_index := abi2_any_hit.find("#define FENG_FOG_RAY_ABI 2")
	_require(provider_source.contains("p_ray_input_abi_version: int = 1")
			and provider_source.contains("RAY_INPUT_ABI_VERSION := 2")
			and provider_source.contains("_ensure_pipeline(p_rd, p_ray_input_abi_version)")
			and provider_source.contains("input_uniform.binding = 1")
			and provider_source.contains("any_hit_input_uniform.binding = 10")
			and provider_source.count("add_id(p_ray_input_buffer)") == 2
			and any_hit_source.contains("layout(set = 0, binding = 10, std430) readonly buffer FogShadowRayInputs")
			and raygen_source.contains("layout(set = 0, binding = 1, std430) readonly buffer FogShadowRayInputs")
			and descriptor_bindings.get("set", -1) == 0
			and descriptor_bindings.get("raygen_input", -1) == 1
			and descriptor_bindings.get("any_hit_input", -1) == 10
			and bool(descriptor_bindings.get("same_borrowed_input_rid", false))
			and not provider_source.contains("_protocol_buffer")
			and not provider_source.contains("protocol_uniform.binding = 10")
			and shader_variant.get("transport") == "compile_time_pipeline_define"
			and shader_variant.get("define") == "FENG_FOG_RAY_ABI"
			and shader_variant.get("accepted_values") == [1, 2]
			and abi1_define_index > abi1_raygen.find("#extension GL_EXT_ray_tracing : require")
			and abi2_define_index > abi2_any_hit.find("#extension GL_EXT_ray_tracing : require")
			and ShadowProvider.shader_source_for_abi(raygen_source, 0).is_empty()
			and ShadowProvider.shader_source_for_abi(any_hit_source, 3).is_empty(),
			"the provider selects ABI 1/2 compile-time stages, reports that contract, and rejects unsupported variants")
	_require(generator_source.contains("SUPPORTS_RAYTRACING_PIPELINE")
			and generator_source.contains("SUPPORTS_BUFFER_DEVICE_ADDRESS")
			and generator_source.contains("source.language = RenderingDevice.SHADER_LANGUAGE_GLSL"),
			"unsupported D3D12-style devices fall back before ray-input compute work")

	var slots_valid := Generator.validate_light_slots(PackedInt32Array([
		Generator.LIGHT_DIRECTIONAL, 1,
		Generator.LIGHT_OMNI, 2,
		Generator.LIGHT_AREA, 0,
	]), Vector4i(2, 3, 0, 1))
	_require(bool(slots_valid.get("valid", false)) and int(slots_valid.get("slot_count", 0)) == 3,
			"native light slots remain in caller-defined light-major order")
	_require(not bool(Generator.validate_light_slots(PackedInt32Array([0, 2]),
			Vector4i(2, 0, 0, 0)).get("valid", true)),
			"out-of-range directional slots fail closed")
	_require(not bool(Generator.validate_light_slots(PackedInt32Array([1, 0, 1, 0]),
			Vector4i(0, 1, 0, 0)).get("valid", true)),
			"duplicate slots cannot silently duplicate or reorder shadow records")
	_require(not bool(Generator.validate_light_slots(PackedInt32Array([4, 0]),
			Vector4i(0, 0, 0, 0)).get("valid", true)),
			"unsupported light types are rejected")
	_require(Generator.flatten_ray_index(2, 5, 64) == 133
			and Generator.flatten_ray_index(1, 64, 64) == -1,
			"flattened records use light-major/froxel-minor indexing with bounds checks")
	var log_params := Vector3(0.25, -3.0, 32.0)
	var slice := 20.5
	var depth := Generator.depth_from_slice(log_params, slice)
	var expected_depth := (pow(2.0, slice / log_params.z) - log_params.y) / log_params.x
	_require(is_equal_approx(depth, expected_depth),
			"log-Z slice center converts to the same view depth as the volume codec")
	_require(Generator.depth_constrained_slice_cpu_oracle(0.0, 0.25, -0.1) == 0.0
			and Generator.depth_from_slice(log_params, -2.0) == Generator.depth_from_slice(log_params, 0.0),
			"front-depth constraint keeps its signed comparison but clamps final slice and reconstructed depth to zero")
	var overhang_uv := Generator.froxel_center_uv(Vector2i(120, 67), Vector2i(1921, 1081), 16)
	_require(overhang_uv.x > 1.0 and overhang_uv.y < 1.0,
			"non-multiple internal sizes preserve the final froxel's pixel-center overhang")
	_require(Generator.max_batch_lights(Vector3i(121, 68, 64)) == 5,
			"128 MiB and trace-count caps expose a safe per-call light batch size")

	var unjittered := Projection.IDENTITY
	unjittered[0] = Vector4(2.0, 3.0, 4.0, 5.0)
	var jittered := Projection.IDENTITY
	jittered[0] = Vector4(9.0, 8.0, 7.0, 6.0)
	var camera := Transform3D(Basis.IDENTITY, Vector3(10.0, 20.0, 30.0))
	var frame := {
		"inverse_projection_unjittered": unjittered,
		"projection": Projection.IDENTITY,
		"inverse_projection": jittered,
		"camera_transform": camera,
		"eye_offset": Vector3(0.25, -0.5, 0.75),
		"internal_size": Vector2i(1921, 1081),
		"near_plane_m": 0.05,
		"far_plane_m": 1000.0,
		"frame_generation": 0x100000001,
		"selected_volume_directional_index": -1,
		"directional_light_count": 2,
		"omni_light_count": 3,
		"spot_light_count": 0,
		"area_light_count": 1,
	}
	var packed := Generator.pack_ray_frame_uniform(frame, Vector3i(121, 68, 64),
			Vector3(0.25, -3.0, 32.0), 16, 3, 1000.0, 0.01,
			Vector2(0.375, 0.625), 0.875)
	_require(packed.size() == 256, "RayFrame UBO is exactly 256 bytes")
	if packed.size() == 256:
		_require(is_equal_approx(packed.decode_float(0), 2.0)
				and is_equal_approx(packed.decode_float(4), 3.0),
				"RayFrame packs the unjittered inverse projection, not TAA jitter")
		_require(is_equal_approx(packed.decode_float(128), 0.25)
				and is_equal_approx(packed.decode_float(136), 0.75),
				"RayFrame keeps the native center-view eye offset in its typed lane")
		_require(is_equal_approx(packed.decode_float(160), 121.0)
				and is_equal_approx(packed.decode_float(172), 0.625)
				and is_equal_approx(packed.decode_float(188), 0.375),
				"RayFrame packs grid and shared XY sample offsets without jittered projection")
		_require(is_equal_approx(packed.decode_float(220), 0.875),
				"RayFrame stores the shared Halton Z offset in its fourth ray-limits lane")
		_require(packed.decode_s32(224) == 2 and packed.decode_s32(228) == 3
				and packed.decode_s32(232) == 0 and packed.decode_s32(236) == 1,
				"RayFrame native light counts preserve directional/local buffer order")
		_require(packed.decode_s32(240) == 3 and packed.decode_s32(244) == 1
				and packed.decode_s32(248) == -1 and packed.decode_s32(252) == 0,
				"RayFrame carries the slot batch, low generation bits, selected sun slot, and disabled extension flag")
	var packed_extension_frame := Generator.pack_ray_frame_uniform(frame,
			Vector3i(121, 68, 64), Vector3(0.25, -3.0, 32.0), 16, 3,
			1000.0, 0.01, Vector2(0.375, 0.625), 0.875, true)
	_require(packed_extension_frame.size() == 256
			and packed_extension_frame.decode_s32(252) == 1,
			"the fixed RayFrame tail enables capsule reads only when same-frame extension bindings are present")
	var depth_packed := Generator.pack_depth_parameters_uniform(frame, true)
	_require(depth_packed.size() == 144,
			"depth projection inputs use the fixed 144-byte auxiliary UBO")
	if depth_packed.size() == 144:
		_require(is_equal_approx(depth_packed.decode_float(0), 1.0)
				and is_equal_approx(depth_packed.decode_float(64), 9.0)
				and is_equal_approx(depth_packed.decode_float(128), 1.0)
				and is_equal_approx(depth_packed.decode_float(132), 0.5)
				and is_equal_approx(depth_packed.decode_float(136), 1.0),
				"depth UBO packs jittered projection/inverse and UE depth-constraint controls")
	var depth_disabled := Generator.pack_depth_parameters_uniform(frame, false)
	_require(depth_disabled.size() == 144 and depth_disabled.decode_float(128) == 0.0,
			"unavailable GBuffer depth is explicitly disabled in the auxiliary UBO")
	_require(is_equal_approx(Generator.depth_constrained_slice_cpu_oracle(10.0, 0.5, 10.6), 10.1)
			and is_equal_approx(Generator.depth_constrained_slice_cpu_oracle(10.0, 0.5, 11.6), 10.5)
			and is_equal_approx(Generator.depth_constrained_slice_cpu_oracle(10.0, 0.5, 9.0), 10.5),
			"CPU oracle applies only a nearer scene depth within the one-slice UE threshold")

	var registry_source := FileAccess.get_file_as_string(
			"res://addons/feng-fog/rendering/raytracing/fog_rt_geometry_registry.gd")
	_require(registry_source.contains("shadow_caster_layer_mask_unavailable")
			and registry_source.contains("layer_mask"),
			"unknown caster masks force full raster fallback instead of layer truncation")
	if _failures == 0:
		print("PASS RT ray input generator (%d checks)" % _checks)
	else:
		push_error("RT ray input generator failed: %d/%d" % [_failures, _checks])
	quit(1 if _failures > 0 else 0)
