#!/usr/bin/env python
import os

# Reuse the godot-cpp checkout vendored inside the terrain addon so we do not
# need a second copy in this repository. SConscripts have no __file__; the
# current working directory is this folder's native/ dir.
NATIVE_ROOT = os.path.abspath(os.getcwd())
GODOT_CPP = os.path.join(
    os.path.dirname(os.path.dirname(NATIVE_ROOT)),  # misc/feng-addons
    "feng-idweight-terrain",
    "native",
    "godot-cpp",
)

env = SConscript(os.path.join(GODOT_CPP, "SConstruct"))

env.Append(CPPPATH=["src/"])
env.Append(CPPPATH=[os.path.join(GODOT_CPP, "gdextension")])
sources = Glob("src/*.cpp")

# Find gdextension path even if the directory or extension is renamed.
from glob import glob

(extension_path,) = glob("../*.gdextension")

addon_path = os.path.dirname(os.path.abspath(extension_path))
project_name = os.path.splitext(os.path.basename(extension_path))[0]

scons_cache_path = os.environ.get("SCONS_CACHE")
if scons_cache_path != None:
    CacheDir(scons_cache_path)
    print("Scons cache enabled... (path: '" + scons_cache_path + "')")

# Embed documentation into the engine
if env["target"] in ["editor", "template_debug"]:
    doc_data = env.GodotCPPDocData("src/gen/doc_data.gen.cpp", source=Glob("doc/doc_classes/*.xml"))
    sources.append(doc_data)

# Create the library target.
debug_or_release = "release" if env["target"] == "template_release" else "debug"
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "{0}/bin/lib{1}.{2}.{3}.framework/{1}.{2}.{3}".format(
            addon_path,
            project_name,
            env["platform"],
            debug_or_release,
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "{}/bin/lib{}.{}.{}.{}{}".format(
            addon_path,
            project_name,
            env["platform"],
            debug_or_release,
            env["arch"],
            env["SHLIBSUFFIX"],
        ),
        source=sources,
    )

Default(library)
